#!/usr/bin/env php
<?php

use Kavinsky\CloverToBitbucket\Command\ReportCommand;
use Symfony\Component\Console\Application;

$loaded = false;

$files = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/vendor/autoload.php',
    getcwd() . 'vendor/autoload.php',
];
foreach ($files as $file) {
    if (file_exists($file)) {
        require_once $file;
        $loaded = true;
        break;
    }
}

if (!$loaded) {
    die('You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL);
}


$application = new class extends Application
{
    public function __construct()
    {
        parent::__construct('CloverToBitbucket', '1.1.1');
    }

    /**
     * Gets the default commands that should always be available.
     *
     * @return \Symfony\Component\Console\Command\Command[] An array of default Command instances
     * @throws \Symfony\Component\Console\Exception\LogicException
     */
    public function getDefaultCommands()
    {
        return [
            ...parent::getDefaultCommands(),
            new ReportCommand(),
        ];
    }
};

$application->run();
